# base_url = "https://qbibubi.dev" i wish lol (one day)
base_url = "https://qbibubi.github.io/qblog/"
title="qbibubi"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
