base_url = "https://qbibubi.github.io"
title = "qbibubi@mycelium:~$"
description = "Mushrooms, hacking, reverse engineering — a terminal of thoughts"

minify_html = true
default_language = "en"
compile_sass = true

[markdown]
