base_url = "https://qbibubi.github.io"
author="qbibubi"
title="qblog"
description="brutalist blog focused on content"

minify_html = true
default_language="en"
compile_sass = true

[markdown]
highlight_code = true
